export const GEMINI_TOOLS_TOKEN = 'GEMINI_TOOLS_TOKEN' as const;
export const SCHEDULER_TOOLS_TOKEN = 'SCHEDULER_TOOLS_TOKEN' as const;
export const PROMPT_DESIGNER_TOOLS_TOKEN =
  'PROMPT_DESIGNER_TOOLS_TOKEN' as const;
